name: Feature to Develop

on:
  push:
    branches:
      - feature

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can change the runner environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your repository's code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Push to develop
        uses: ad-m/github-push-action@feature
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
