on:
  push:
    branches:
      - feature
  pull_request:
    branches: 
      - main
      - develop

env:
  AZURE_WEBAPP_NAME: L5-M3-Test
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/develop'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Deploy to Azure Webapp Test (L5-M3-Test)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Set output URL for next steps
        run: echo "WEBAPP_URL=$WEBAPP_URL" >> $GITHUB_ENV

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Deploy to Azure Webapp Production (L5-M3-2)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Set output URL for next steps
        run: echo "WEBAPP_URL=$WEBAPP_URL" >> $GITHUB_ENV
